"""add consitency constraints on exit_price+closed_at and exit_price+profit_and_loss

Revision ID: 0ce59b2f9714
Revises: 1918149c6379
Create Date: 2026-05-26 19:24:08.679539

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ce59b2f9714"
down_revision: Union[str, Sequence[str], None] = "1918149c6379"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_exit_price_and_closed_at_consistency",
        "trades",
        "(exit_price IS NULL AND closed_at IS NULL) OR "
        "(exit_price IS NOT NULL AND closed_at IS NOT NULL)",
    )
    op.create_check_constraint(
        "check_profit_and_loss_consistency",
        "trades",
        "(exit_price IS NULL AND profit_and_loss IS NULL) OR "
        "(exit_price IS NOT NULL AND profit_and_loss IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "check_exit_price_and_closed_at_consistency", "trades", type_="check"
    )
    op.drop_constraint("check_profit_and_loss_consistency", "trades", type_="check")
    # ### end Alembic commands ###
