"""add closed_at constraint to trade table

Revision ID: 1918149c6379
Revises: 770559965462
Create Date: 2026-05-25 13:41:19.295794

"""

from typing import Sequence, Union

# import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1918149c6379"
down_revision: Union[str, Sequence[str], None] = "770559965462"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_closed_at_after_opened_at",
        "trades",
        "closed_at IS NULL OR closed_at >= opened_at",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_closed_at_after_opened_at", "trades", type_="check")
    # ### end Alembic commands ###
