"""add revoked bool column

Revision ID: 2f4d8252d768
Revises: 25d85455473b
Create Date: 2026-05-22 13:50:20.661907

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f4d8252d768"
down_revision: Union[str, Sequence[str], None] = "25d85455473b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "revoked",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.create_index(
        op.f("ix_refresh_tokens_revoked"), "refresh_tokens", ["revoked"], unique=False
    )
    op.alter_column("refresh_tokens", "revoked", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_revoked"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "revoked")
    # ### end Alembic commands ###
