"""add check constraint on confidence column?

Revision ID: aa4f39513004
Revises: 5e5248ead62c
Create Date: 2026-06-05 09:39:42.077075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa4f39513004"
down_revision: Union[str, Sequence[str], None] = "5e5248ead62c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "check_confidence_range",
        "sentiment_analysis",
        "confidence > 0.0 AND confidence < 1.0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_confidence_range", "sentiment_analysis", type_="check")
    # ### end Alembic commands ###
