"""add missing columns to sentiment_analysis

Revision ID: 5e5248ead62c
Revises: 442810046932
Create Date: 2026-06-05 09:27:58.761709
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e5248ead62c"
down_revision: Union[str, Sequence[str], None] = "442810046932"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sentiment_analysis",
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
    )
    op.add_column(
        "sentiment_analysis",
        sa.Column("journal_entry_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        "fk_sentiment_analysis_journal_entry_id",
        "sentiment_analysis",
        "journal_entries",
        ["journal_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "uq_sentiment_analysis_journal_entry_id",
        "sentiment_analysis",
        ["journal_entry_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_sentiment_analysis_journal_entry_id", "sentiment_analysis", type_="unique"
    )
    op.drop_constraint(
        "fk_sentiment_analysis_journal_entry_id",
        "sentiment_analysis",
        type_="foreignkey",
    )
    op.drop_column("sentiment_analysis", "journal_entry_id")
    op.drop_column("sentiment_analysis", "confidence")
    # ### end Alembic commands ###
