"""initial migration

Revision ID: f30697351f99
Revises:
Create Date: 2026-05-19 15:07:16.596068

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f30697351f99"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
